# Generated by Django 4.2.7 on 2025-12-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevyseg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('horas', models.PositiveIntegerField()),
                ('profesor', models.CharField(max_length=150)),
                ('valor', models.PositiveIntegerField()),
                ('tipo_certificado', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('cupos_disponibles', models.PositiveIntegerField()),
                ('documentos_requeridos', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Online', 'Online'), ('Mixto', 'Mixto')], default='Presencial', max_length=20)),
                ('area', models.CharField(choices=[('seguridad', 'Seguridad Privada'), ('administracion', 'Administración y Finanzas'), ('tecnologia', 'Tecnología y Sistemas'), ('oficios', 'Oficios Técnicos'), ('alimentos', 'Alimentos y Manipulación'), ('estetica', 'Belleza y Estética')], default='seguridad', max_length=20)),
            ],
        ),
    ]
