# Generated by Django 4.2.7 on 2025-12-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevyseg_app', '0002_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='dias_semana',
            field=models.CharField(blank=True, help_text='Días de la semana separados por comas (ej: Lunes,Miércoles,Viernes)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
