# Generated by Django 4.2.7 on 2025-12-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevyseg_app', '0003_curso_dias_semana_curso_hora_fin_curso_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('por_empezar', 'Por Empezar'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='por_empezar', help_text='Estado actual del curso', max_length=20),
        ),
    ]
