# Generated by Django 5.2.8 on 2025-12-05 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevyseg_app', '0004_curso_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_doc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoSubido',
            fields=[
                ('id_doc_subido', models.AutoField(primary_key=True, serialize=False)),
                ('url_archivo', models.FileField(upload_to='documentos/')),
                ('estado_revision', models.CharField(choices=[('APROBADO', 'Aprobado'), ('EN_REVISION', 'En revisión'), ('RECHAZADO', 'Rechazado')], default='EN_REVISION', max_length=20)),
                ('observaciones_rechazo', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prevyseg_app.tipodocumento')),
            ],
        ),
    ]
