# Generated by Django 5.2.8 on 2025-12-08 22:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevyseg_app', '0005_tipodocumento_documentosubido'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosubido',
            name='curso',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='prevyseg_app.curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentosubido',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InscripcionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('iNSCRITO', 'Inscrito'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'FINALIZADO')], default='INSCRITO', max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prevyseg_app.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'curso')},
            },
        ),
    ]
