# Generated by Django 5.2.8 on 2025-12-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevyseg_app', '0006_documentosubido_curso_documentosubido_fecha_subida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='documentos_requeridos',
        ),
        migrations.AddField(
            model_name='curso',
            name='documentos_requeridos',
            field=models.ManyToManyField(blank=True, help_text='Documentos requeridos para inscribirse ', related_name='cursos', to='prevyseg_app.tipodocumento'),
        ),
    ]
