# Generated by Django 5.2.8 on 2025-12-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevyseg_app', '0007_remove_curso_documentos_requeridos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='estado',
            field=models.CharField(choices=[('INSCRITO', 'Inscrito'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'FINALIZADO')], default='INSCRITO', max_length=20),
        ),
    ]
