# Generated by Django 6.0 on 2025-12-16 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevyseg_app', '0008_alter_inscripcioncurso_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='dias_semana',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='hora_inicio',
        ),
        migrations.CreateModel(
            name='HorarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='prevyseg_app.curso')),
            ],
        ),
    ]
