# Generated by Django 5.2.8 on 2025-12-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevyseg_app', '0009_remove_curso_dias_semana_remove_curso_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcioncurso',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='monto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscripcioncurso',
            name='token_ws',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
