# Generated by Django 5.2.8 on 2025-12-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevyseg_app', '0010_inscripcioncurso_fecha_pago_inscripcioncurso_monto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcioncurso',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('INSCRITO', 'Inscrito'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'FINALIZADO')], default='INSCRITO', max_length=20),
        ),
    ]
