# Generated by Django 5.2.8 on 2025-12-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevyseg_app', '0011_alter_inscripcioncurso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo_sence',
            field=models.CharField(blank=True, help_text='Código SENCE oficial del curso', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='horas_sence',
            field=models.PositiveIntegerField(blank=True, help_text='Horas cronológicas reconocidas por SENCE', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='valor_hora_sence',
            field=models.PositiveIntegerField(blank=True, help_text='Valor hora SENCE para franquicia tributaria', null=True),
        ),
    ]
