# Generated by Django 5.2.8 on 2025-12-24 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevyseg_app', '0012_curso_codigo_sence_curso_horas_sence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('metodo', models.CharField(choices=[('Manual', 'Manual'), ('Biometrico', 'Biometrico')], default='Manual', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prevyseg_app.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', 'hora_entrada'],
                'unique_together': {('usuario', 'curso', 'fecha')},
            },
        ),
    ]
